name: "Default"
on:
  push:
jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        output:
          [ packages.x86_64-linux.default
          , devShells.x86_64-linux.default
          ]
    steps:
    - name: "Set up GitHub Actions"
      uses: actions/checkout@v3.0.2
    - name: "Set up Nix"
      uses: cachix/install-nix-action@v17
    - name: "Set up Cachix"
      uses: cachix/cachix-action@v12
      with:
        name: jumper149-deriving-trans
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: "Build"
      run: nix build --print-build-logs .\#${{ matrix.output }}
  check:
    name: "Check Flake"
    runs-on: ubuntu-latest
    steps:
    - name: "Set up GitHub Actions"
      uses: actions/checkout@v3.0.2
    - name: "Set up Nix"
      uses: cachix/install-nix-action@v17
    - name: "Set up Cachix"
      uses: cachix/cachix-action@v12
      with:
        name: jumper149-deriving-trans
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: "Check"
      run: nix flake check --keep-going --print-build-logs
